### ISSUE TITLE
Is buying selling an R1 things?

### ISSUE THREAD

**Issue by vuzDylan** [TeamMartinez/YOLO-Client#33]
?

**Comment by jonobrien** [comment]
the project page infor for R1 stocks:
- Stock ticker (Retrieve information from existing external API's)
- You should have a stock page for any ticket symbols that the user may "punch in". 

Displayed data should include:
(already in #25 )
- Current price
- Day's high
- Day's low
- Yearly high
- Yearly low
- An interactive chart of the stock (not just a retrieved image)

The `stock report` section at the top of the doc, however, lists buying/selling fake stocks as part of the page/component requirement.

I would say no because that would involve storage in the db which is an R2 requirement.

**Comment by mok4ry** [comment]
It's an R2 feature, not R1.
